<?PHP
$wzor[0]= array ("ratusz"   => 5,
               "koszary"  => 3,
               "stajnie"  => 0,
               "warsztat" => 0,
               "palac"    => 0,
               "kuznia"   => 1,
               "plac"     => 1,
              "piedestal" => 0,
               "rynek"    => 0,
               "tartak"   => 10,
              "cegielnia" => 10,
               "huta"     => 10,
               "zagroda"  => 10,
              "spichlerz" => 15,
               "schowek"  => 0,
               "mur"      => 1
               );
                                      // maly obronca
$wzor[1]= array ("ratusz"   => 10,
               "koszary"  => 5,
               "stajnie"  => 1,
               "warsztat" => 0,
               "palac"    => 0,
               "kuznia"   => 5,
               "plac"     => 1,
              "piedestal" => 0,
               "rynek"    => 0,
               "tartak"   => 10,
              "cegielnia" => 10,
               "huta"     => 10,
               "zagroda"  => 20,
              "spichlerz" => 20,
               "schowek"  => 0,
               "mur"      => 10
               );

$wzor[2]= array ("ratusz"   => 10,
               "koszary"  => 10,
               "stajnie"  => 5,
               "warsztat" => 0,
               "palac"    => 0,
               "kuznia"   => 5,
               "plac"     => 1,
              "piedestal" => 0,
               "rynek"    => 3,
               "tartak"   => 10,
              "cegielnia" => 10,
               "huta"     => 10,
               "zagroda"  => 30,
              "spichlerz" => 25,
               "schowek"  => 0,
               "mur"      => 20
               );

$wzor[3]= array ("ratusz"   => 15,
               "koszary"  => 10,
               "stajnie"  => 10,
               "warsztat" => 1,
               "palac"    => 0,
               "kuznia"   => 10,
               "plac"     => 1,
              "piedestal" => 0,
               "rynek"    => 3,
               "tartak"   => 15,
              "cegielnia" => 15,
               "huta"     => 15,
               "zagroda"  => 30,
              "spichlerz" => 25,
               "schowek"  => 0,
               "mur"      => 20
               );
// DUZY Obronca
$wzor[4]= array ("ratusz"   => 22,
               "koszary"  => 25,
               "stajnie"  => 20,
               "warsztat" => 0,
               "palac"    => 1,
               "kuznia"   => 20,
               "plac"     => 1,
              "piedestal" => 0,
               "rynek"    => 15,
               "tartak"   => 30,
              "cegielnia" => 30,
               "huta"     => 30,
               "zagroda"  => 30,
              "spichlerz" => 30,
               "schowek"  => 0,
               "mur"      => 20
               );


$wzor[5]= array (    "ratusz"   => 30,
               "koszary"  => 25,
               "stajnie"  => 20,
               "warsztat" => 5,
               "palac"    => 1,
               "kuznia"   => 20,
               "plac"     => 1,
              "piedestal" => 0,
               "rynek"    => 15,
               "tartak"   => 30,
              "cegielnia" => 30,
               "huta"     => 30,
               "zagroda"  => 30,
              "spichlerz" => 30,
               "schowek"  => 0,
               "mur"      => 20
               );

  // mix max
$wzor[6]= array (   "ratusz"   => 30,
               "koszary"  => 25,
               "stajnie"  => 20,
               "warsztat" => 1,
               "palac"    => 1,
               "kuznia"   => 20,
               "plac"     => 1,
              "piedestal" => 0,
               "rynek"    => 25,
               "tartak"   => 30,
              "cegielnia" => 30,
               "huta"     => 30,
               "zagroda"  => 30,
              "spichlerz" => 30,
               "schowek"  => 0,
               "mur"      => 20
               );
?>